### ISSUE TITLE
HTTP client: support TLS

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#1311]
Add TLS support for the HTTP client.  This is only so that nodes can request blocks and transactions from HTTPS servers.  The data being requested is already public, so I don't care too much about avoiding an implementation that might have latent side-channels (but I care a _lot_ about avoiding an implementation that might have latent buffer overflows, or other kinds of remotely-exploitable flaws).

**Comment by CharlieC3** [comment]
Reopening this issue. We'd like to be able to host seeds using TLS, where termination occurs in a proxy placed in front of the seed, however this is not currently possible in node to node communication.
While `https://my-seed.domain.com:20443/v2/info` would resolve just fine for me in this setup, the configured `data_url` property on the seed currently only supports an IP address, and would resemble something like `https://1.2.3.4:20443`

Stacks nodes connecting to this data_url will hit this error:
```
Got bad HTTP response from UrlString("https://1.2.3.4:20443/"): ServiceUnavailable(HttpResponseMetadata { client_version: Http11, client_keep_alive: true, request_id: 0, content_length: Some(95), canonical_stacks_tip_height: None }, "upstream connect error or disconnect/reset before headers. reset reason: connection termination")
```

It's not clear to me if this is caused by the self-signed TLS cert needed to reach the seed over IP using TLS (acquiring a TLS cert for an IP address is quite difficult and not a great solution), or if this is generally caused by insufficient support for TLS comms as a whole.

I think ideally, the `data_url` config would be updated to allow DNS records as input, and a new option would be provided to ignore invalid TLS connections caused by self-signed certificates.

**Comment by jcnelson** [comment]
I didn't comment on this earlier because the stale bot took care of closing the issue, but there's no longer any desire on my end for TLS on the data-plane.  The p2p control-plane messages are all self-signed anyway and nodes do key exchange via TOFU, and all data-plane messages that are necessary for nodes to keep in sync with one another don't need to be authenticated because the requester already has the cryptographic hash of the data being requested.

> the configured data_url property on the seed currently only supports an IP address, and would resemble something like https://1.2.3.4:20443

That's odd.  The p2p protocol definitely supports the exchange of (reasonably-sized) HTTP URLs, which may include both DNS names and paths.  The config logic doesn't try and convert the `data_url` string into a bare IP address either -- it just uses it as-is and passes it into the peer DB, which the node will then use when it carries out handshakes with remote nodes.

Can you tell me what happens if you try and put an HTTP URL with a DNS name for your `data_url`?

> It's not clear to me if this is caused by the self-signed TLS cert needed to reach the seed over IP using TLS (acquiring a TLS cert for an IP address is quite difficult and not a great solution), or if this is generally caused by insufficient support for TLS comms as a whole.

It's the latter.  Your node sent a bare HTTP request to that endpoint, and the endpoint closed the socket because it wasn't a TLS handshake.

> I think ideally, the data_url config would be updated to allow DNS records as input, and a new option would be provided to ignore invalid TLS connections caused by self-signed certificates.

I don't think TLS is ever going to be supported by the node.  It adds a lot of implementation complexity (and attack surface area) for only marginal gain.

But, DNS-named nodes as `data_url`s should already be supported.  If it's not, then that's definitely a worthy bug report.

**Comment by CharlieC3** [comment]
@jcnelson Actually it seems setting the `data_url` to a domain works fine. I tested this a few months ago, and I'm guessing it didn't work back then because TLS was configured at the time.
