### ISSUE TITLE
Ability to profile API endpoints in Prometheus

### ISSUE THREAD

**Issue by lgalabru** [stacks-network/stacks-blockchain#1818]
For each API endpoint, we should be able to have a distribution of the response time, along with a break down of where the time is being spent (we probably want a per-DB granularity).
We'll probably want something similar in the `ChainsCoordinator` at some point, so we can get some profiling for events such as new burnchain block and new stacks block.

I think ideally we'd want to be able to create some newrelic-like reports in Prometheus (applied to our context of course).

![maxresdefault](https://user-images.githubusercontent.com/87777/90669359-8915eb00-e21f-11ea-8d63-5d5979eb29fa.jpg)

**Comment by diwakergupta** [comment]
I think we still want this

**Comment by zone117x** [comment]
New Relic or Datadog equivalents within our own infra would be super useful

**Comment by CharlieC3** [comment]
https://github.com/opentracing/opentracing-rust

**Comment by diwakergupta** [comment]
Another relevant repo is: https://github.com/tokio-rs/tracing

BTW opentracing merged with another project to become https://opentelemetry.io/

**Comment by jcnelson** [comment]
We're trying to *get off of* tokio and async-std, so the first link is a non-starter.  Opentracing is marked as under initial development and experimental, so that's not something that we should let anywhere near the blockchain (where hundreds of millions of dollars of other peoples' money is at stake).

Is there something we can use that doesn't pull in half of the entire Rust ecosystem and thousands of lines of `unsafe` code?  Like, why is it so difficult to just add some basic instrumentation hooks, like the following:

```
let t_before = get_epoch_time_ms();
/* do the thing */
let t_total = get_epoch_time_ms().saturating_sub(t_before);
perf_trace!(PerfTraceToken::THE_THING_WE_TRACED, t_total);
```

where `perf_trace!` just emits a trace identifier and a total-time taken to a downstream consumer, such as writing it to a given file descriptor.
