### ISSUE TITLE
PoX updates: `stack-decrease`

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-blockchain#2649]
In addition to being able to increase your stack #2533 , it would be valuable to be able to decrease your stack, without having to completely un-stack. I'm not sure if this is already considered or not, so apologies if this is duplicated.

```clar
;; decrease the amount in "tx-sender"s active lockup
(define-public (stack-decrease (decrease-by uint)))
;; decrease the amount in a delegated active lockup
(define-public (delegate-stack-increase (stacker principal) (decrease-by uint)))
```

**Comment by unclemantis** [comment]
I do not agree with with feature request. But let the consensus do it's work.

**Comment by unclemantis** [comment]
DEEP ANALYSIS


The whole idea of stacking is to leave your delegated STX alone and let the system reward you accordingly. If one where to decrease their allowance then idea of stacking is pointless. When one stacks they LOCK their STX for a duration of cycles.  At the end of the agreed stacking duration, stx are released and you are rewarded with x amount of reward tokens.  If one where to decrease their stake then what happens? Are your STX returned to you immediately or are they still locked? Can one decrease the stacked stx amount to zero and get all their stx back and give up any rewards for that cycle and the future stacked cycles? Would a one cycle cool down be in effect or one cycle plus the remaining cycles in your initial delegation be the cool down period?

I am against  to such a feature. One could like stack an enormous amount for 12 cycles or so and then pull out after one cycle? How would that affect the rewards to the other stackers?

**Comment by jcnelson** [comment]
I don't think `stack-decrease` is going to happen anytime soon.  It would require substantial portions of the PoX code -- both the contract and the node -- to be rewritten, since in many places we assume that the total locked STX and the per-address locked STX can only increase.  Allowing decreases would require us to reason about a whole host of denial-of-service vulnerabilities that cannot happen right now.  For example, someone could stall the network at each reward cycle boundary by creating an ungodly-gigantic set of PoX addresses to consider if they were able to use a combination of `stack-stx` and `stack-decrease` to effectively stack one uSTX per distinct PoX address (something the current code prevents with a stacking minimum).

**Comment by jcnelson** [comment]
Per the linked SIP discussion, it seems to me that `stack-decrease` is unnecessary if you instead have `transfer-and-stack-stx`.  That is much less challenging and much less risky to implement.

**Comment by hstove** [comment]
I would agree that `transfer-and-stack-stx` would basically negate the need. Is there a realistic path to that getting included? Should I start a SIP?

**Comment by jcnelson** [comment]
Can you open an issue for it and link the discussion?  I'm not sure if we'll have time to get it added to `next` before the freeze, but I'd be willing to review a PR that adds it.  We don't have a deadline yet for the `next` freeze, but if [this proposal](https://github.com/stacks-network/stacks-blockchain/discussions/3083#discussioncomment-2689101) is the one we get behind for the next network upgrade, it'll need to be done in parallel to these remaining work items.

**Comment by jcnelson** [comment]
This is not going to be implemented for the foreseeable future due to the technical challenges and low activity on this issue.

If this is still needed, can you re-open an issue for `transfer-and-stack-stx`?  Thanks!
