### ISSUE TITLE
Re-emit last failed event after startup

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-blockchain#2813]
**Is your feature request related to a problem? Please describe.**
When shutting down a running stacks-blockchain-api and stacks-node, a specific order must always be followed; the stacks-node must be shut down first and the API last. If this is performed out of order, it introduces the risk where the API is down and unable to accept a new TX or block from the stacks-node.

When both services are brought back up, the stacks-node does _not_ attempt to resend the previous TX or block which failed to send earlier, and instead will just send the newest event. This can cause unrecoverable corruption in the API's database, forcing a wipe of the API's db and stacks-node's working directory.

**Describe the solution you'd like**
If configured to emit events, the stacks-node will remember the previous TX or block which failed to send to any of its configured APIs, and will re-attempt to send the TX or block again when starting back up.

**Describe alternatives you've considered**
Other alternatives could help, but would likely be less effective. Extra documentation can be written, but not all would see it.

**Comment by gregorycoppola** [comment]
This makes sense as a request. But, we should evaluate how necessary this is, because it is a heavy-weight request.

**Comment by zone117x** [comment]
If I understand correctly, the code is currently doing something like the following:
1. Process block, keep a bunch of ephemeral event-related data in memory, write to disk with finality (all the work for this block is considered done).
2. Grab that ephemeral in-memory data and broadcast event(s), retry forever in a loop if the HTTP POST fails.
3. If in an HTTP POST retry-loop the stacks-node will not graceful shutdown, and eventually its container will be force killed.
4. On reboot, that last block is considered "done", all the ephemeral in-memory data gone, and event observers have an unrecoverable gap in chain data.


Is this understanding correct? And if so, can step 1 be modified so that block processing is not considered final until _after_ the event(s) have been successfully broadcasted? This way when the stacks node is restarted, it will pick up where it left off in the event dispatch loop.

**Comment by kantai** [comment]
> Is this understanding correct? And if so, can step 1 be modified so that block processing is not considered final until after the event(s) have been successfully broadcasted? This way when the stacks node is restarted, it will pick up where it left off in the event dispatch loop.

Yes -- this understanding is correct. However, refactoring the block processing so that the block isn't marked "processed" until after the event processor could prove to be a fairly involved change: block processing updates the clarity db and the block metadata db, and I believe the event receipts are only available once the clarity db commits. It's probably possible, but it would be a delicate change. The reason I say "probably possible" is that the stacks-node's processing logic _isn't_ entirely "transactional" in the way that, for example, a SQL database is. This is why we have the graceful exit command -- it sends an exit signal to the various threads so that they can continue processing until they can safely stop. So if the API event dispatcher causes an "abort", it's not obviously true that processing can be stopped/rolled-back at that point.

However, in the event of graceful shutdowns, it should be possible for the event dispatcher to just stash the final failed event (if one exists) before closing and attempt to broadcast it on restart. I believe there's already a buggy behavior in the described case here: graceful shutdown will ask the block processing thread to shut down, but that thread is trying to broadcast an event (retrying, waiting for response, etc.), and eventually the process exits unsafely.

**Comment by jcnelson** [comment]
What if we stored transaction event data as an optional column of serialized JSON in the `transactions` table?  Then, it would just be available for querying for nodes who want to maintain a transaction log (which would include Hiro's nodes).

**Comment by kantai** [comment]
> What if we stored transaction event data as an optional column of serialized JSON in the transactions table? Then, it would just be available for querying for nodes who want to maintain a transaction log (which would include Hiro's nodes).

Transaction event data could be fairly large, and would need to be stored by StacksBlockId. The stacks-node would also _still_ need to do at least the following:

1. Alert the event listener on restart of the last event sent (otherwise, the event listener doesn't even know to query for data that it missed).
2. Modify the event dispatcher retry logic to check if the graceful shutdown has been invoked, and continue (rather than retry or panic) the shutdown routine after the first failed dispatch.

**Comment by zone117x** [comment]
It may be good enough to only store the latest event json data, and mark it as "not emitted" when shutdown during event-dispatch failures. When the stacks-node is started, it could just resume the event dispatch retry that it exited with.

**Comment by CharlieC3** [comment]
@pavitthrap Does https://github.com/stacks-network/stacks-blockchain/pull/3047 transitively fix this issue too?

**Comment by jcnelson** [comment]
Temporarily assigning to @pavitthrap so this has an owner.  This might be fixed transitively, but needs confirmation.  Please feel free to re-assign.
