### ISSUE TITLE
Recovery from underflow, overflows, division by zero

### ISSUE THREAD

**Issue by MarvinJanssen** [stacks-network/stacks-blockchain#2852]
Sometimes it is useful to be able to recover from underflow and overflow errors.

The proposal is to introduce equivalents for all arithmetic functions that return an `(ok int | uint)` on success and `(err uint)` on failure.

| Function | Recoverable equivalent |
|-|-|
| `+` | `+?` |
| `-` | `-?` |
| `*` | `*?` |
| `/` | `/?` |
| `mod` | `mod?` |
| `pow` | `pow?` |
| `to-int` | `to-int?` |
| `to-uint` | `to-uint?` |

**Error codes**

| Error code | Description |
|-|-|
| `u0` | Underflow |
| `u1` | Overflow |
| `u2` | Division by zero |

**Examples**

```clojure
>(+? u5 u6)
(ok u11)

>(+? MAX_UINT u1)
(err u1)

>(-? 4 9)
(ok -4)

>(-? MIN_INT 1)
(err u0)

>(to-uint? 20)
(ok u20)

>(to-uint? -50)
(err u0)
```

And so on.

**Comment by fiftyeightandeight** [comment]
One concern is that the numerical error codes could be confusing.
The alternative may be to return none in case of error, but then we lose the information on the cause of the error.
On balance, however, I think the latter is better than the former, if we have to pick one, because what is more important is we catch and handle the error (whichever error it was) than knowing what error it was (however helpful).
Open to other (better) suggestions, of course!

**Comment by jcnelson** [comment]
@MarvinJanssen Can you move this to the Clarity language reference repo?  Thanks!  https://github.com/clarity-lang/reference/issues
