### ISSUE TITLE
Check if CircleCi is still used 

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-blockchain#3072]
from readme, circleci image is 404'ing https://circleci.com/gh/blockstack/stacks-blockchain/tree/master.
Is this CI tool still used ? i see the circleci yaml, and a Dockerfile but there's no action using them and the circle links are not working https://github.com/stacks-network/stacks-blockchain#stacks-20

TODO: check if circleci is still in use. if yes, update links etc in the readme. 
if not in use, then we can remove all references to circleci and Hiro can disable any jobs still there.

**Comment by jcnelson** [comment]
Consensus here is "no."  CircleCI invoked our unit tests using `cargo test --workspace`, whereas previously unit tests in GH actions invoked `cargo test`.  But because `develop` broke the workspace into more modules, GH needed to invoke `cargo test --workspace` anyway, so CircleCI doesn't do anything useful for us anymore.  We can remove CircleCI support in the next release (or even now).

**Comment by diwakergupta** [comment]
The last activity on https://app.circleci.com/pipelines/github/stacks-network/stacks-blockchain was 3 months ago. Is it safe to cancel the paid plan (which Hiro is currently paying for) and close this issue? cc/ @jcnelson @kantai

**Comment by kantai** [comment]
Yes, let's close it.

**Comment by kantai** [comment]
Should this file be deleted before we close this issue?

https://github.com/stacks-network/stacks-blockchain/blob/master/circle.yml

**Comment by diwakergupta** [comment]
Nothing has run on CircleCI for ~11mo, so yeah let's do it. I'm happy to take this on ;)
