### ISSUE TITLE
Add `shutdown` RPC endpoint

### ISSUE THREAD

**Issue by whoabuddy** [stacks-network/stacks-blockchain#3076]
**Is your feature request related to a problem? Please describe.**

When running a node via Docker it is difficult to stop a node without resulting in data corruption.

**Describe the solution you'd like**

Add an RPC endpoint that accepts a shutdown request then gracefully shuts down the node.

**Describe alternatives you've considered**

If running a single node via Docker then corrupting the chain state means having to sync again from scratch.

Since Docker is the recommended method for running a node, and some services may only run one node to start with before scaling up, this could be an easy way to allow single node operators to stop their operations and clone the chain state to use with multiple nodes.

**Comment by CharlieC3** [comment]
For posterity, I can confirm the stacks-node already detects `SIGTERM` signals to know when to shut down, and is able to detect this through running `docker stop...`. If the `SIGTERM` is not reaching the main process, that usually indicates it's getting caught in a superseding shell.
This is pretty common when the default `CMD` directive from the Dockerfile is being overridden in the shell form instead of the exec form.
```bash
# shell form
CMD "stacks-node mainnet"

# exec form
CMD ["stacks-node", "mainnet"]
```

Using the exec form, whether it's in a Dockerfile, docker-compose, for Kubernetes config file, should resolve this problem and allow the `stacks-node` main process to detect signals.

**Comment by wileyj** [comment]
> For posterity, I can confirm the stacks-node already detects `SIGTERM` signals to know when to shut down, and is able to detect this through running `docker stop...`. If the `SIGTERM` is not reaching the main process, that usually indicates it's getting caught in a superseding shell. This is pretty common when the default `CMD` directive from the Dockerfile is being overridden in the shell form instead of the exec form.
> 
> ```shell
> # shell form
> CMD "stacks-node mainnet"
> 
> # exec form
> CMD ["stacks-node", "mainnet"]
> ```
> 
> Using the exec form, whether it's in a Dockerfile, docker-compose, for Kubernetes config file, should resolve this problem and allow the `stacks-node` main process to detect signals.

indeed - i'm testing some changes for this exactly, trying to find a good timeout for the shutdown sequence.

**Comment by wileyj** [comment]
@whoabuddy still working out the timing - I'm syncing a node to run some tests, but so far there is a long timeout required during the sync process since the event-observer loop can take a while to shut down correctly. 
I've seen anywhere from a few seconds to a little more than 10 minutes - for now, the default is being set to 20 minutes to address this (i'm curious to see if how those numbers change once the node is fully synced - i expect the timing to be much less than what i'm seeing during a sync).

**Comment by wileyj** [comment]
still syncing....probably won't have any info until blockchain meeting on 3/28

**Comment by whoabuddy** [comment]
@wileyj sounds good. If I can test anything with my node as well I'm willing - I'd like to create a backup of the chain state anyway!

**Comment by wileyj** [comment]
nothing at the moment - i'm still a few thousand blocks behind chain tip, so far the timing during a sync is "known" - i'm syncing the chain with an API using the following env vars:
```
STACKS_API_ENABLE_FT_METADATA=1
STACKS_API_ENABLE_NFT_METADATA=1
```
which is greatly increasing the sync time. However, i felt this was necessary to see if the shutdown takes longer.
Eventually, the following line will have an extra option `-t <int>` once the the timing is found:
https://github.com/stacks-network/stacks-blockchain-docker/blob/master/manage.sh#L150

I've also been working off of this branch (which also gets rid of the positional args in favor or option parsing): https://github.com/stacks-network/stacks-blockchain-docker/blob/feat/option-parsing/manage.sh#L215



You *can* try to add some timing there if you're so inclined, but until we have a baseline it may end up corrupting the chainstate (it's not too likely, but i've been able to corrupt it myself with too low of a timeout).
