### ISSUE TITLE
LRU cache strategy for the MARF

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3088]
Add an LRU cache strategy for the MARF to see if it speeds up transaction mining.

**Comment by gregorycoppola** [comment]
There are several ways to approach this overall strategy.

The benefits of caching key/value (K, V), valid as of block B1, needed to produce block B2, will only be realized if:
* the value has been cached before B2
* the value has not changed since B1

I would ask:
* What opportunities does the system have to add this value to the cache? e.g., can we pre-process a transaction? or are we only caching when trying to produce a block the same as now? pre-processing could even happen in multiple threads.
* Can the cache be structured so that it solves https://github.com/stacks-network/stacks-blockchain/issues/3074. That is, can we remember the values we read on checkpoint `k`, to help with checkpoint `k+1`, even if they might have been over-written to produce checkpoint `k`.

**Comment by jcnelson** [comment]
Actually, this issue is premature.  There's still a lot we can do to make sure the I/O channels are saturated with goodput when reading and writing the MARF.
