### ISSUE TITLE
Can `info!`-style logs print human-readable time?

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#3206]
**Is your feature request related to a problem? Please describe.**
The logs currently print the time by counting epoch seconds, so it is hard to understand what time it really is in a log:

```
INFO [1658334748.441666] [testnet/stacks-node/src/neon_node.rs:1456] [main] Start HTTP server on: 0.0.0.0:20443
```

Can we make this so that the logs print the time in an easily human readable?

**Describe the solution you'd like**
 I'm not sure of the solution.

**Comment by jcnelson** [comment]
The reason it prints a UNIX time stamp is because I often find myself comparing _relative_ times between events, in order to determine how long it takes for the node to do something.  This has been instrumental in finding slow code in hot paths.

As an alternative, it's straightforward to write a script that just converts the UNIX timestamp column into an ISO 8601 timestamp.  You could do this in `awk` for example.

**Comment by gregorycoppola** [comment]
@jcnelson Is there a Rust change I can make in a local branch to get the "human readable" forms?

I wanted to do the same thing you are saying (calculate difference between two events), but I just found it harder to think in absolute seconds. E.g., I expect 6 new blocks per hour.

**Comment by kantai** [comment]
Look at https://github.com/stacks-network/stacks-blockchain/blob/master/stacks-common/src/util/log.rs#L44

**Comment by igorsyl** [comment]
https://github.com/stacks-network/stacks-blockchain/pull/3219

**Comment by jcnelson** [comment]
This is now live!

**Comment by gregorycoppola** [comment]
Nice
