### ISSUE TITLE
Node stalled "No header for child block [], so will not validate continuity" 

### ISSUE THREAD

**Issue by MaksimalistT** [stacks-network/stacks-blockchain#3259]
**Describe the bug**
Node in follower mode appears to be stalled on testnet
debug msg potentially related to the issue
DEBG [1661080158.612751] [src/burnchains/bitcoin/spv.rs:957] [ThreadId(3)] No header for child block 2343149, so will not validate continuity

**Steps To Reproduce**
occurs from time to time, restart helps to fix the issue

**Expected behavior**
Node doesn't stall every time it is started

**Environment (please complete the following information):**
 - OS: Amazon Linux
 - rustc 1.61.0
 - 2.05.0.2.2

**Comment by jcnelson** [comment]
Update: still looking into this

**Comment by jcnelson** [comment]
This seems to be related to #3252.  There are a couple other things I'm working on that take precedence, but once I have a chance to dig through the logs posted in #3252 I can get back to this.  Thanks for being patient!

**Comment by jcnelson** [comment]
We haven't seen this issue in our infrastructure.  The 2.05.0.6.0 release made some significant changes to ensuring that the miner is always kept up-to-date with the Bitcoin and Stacks tips (I see that this report was for 2.05.0.2.2).  Going to close this due to inactivity.  If you see this happen in 2.05.0.6.0, please re-open.  Thanks!
