### ISSUE TITLE
[Stacks 2.1] Improve pox function signatures

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-blockchain#3331]
**Is your feature request related to a problem? Please describe.**
A) I am frustrated to see error codes of type int while other contracts return uint
B) I am frustrated that pool members can't specify where they want to receive their stacking rewards

**Describe the solution you'd like**
In pox-2, change error code to uint (A) and add a parameter in delegate-stx similar to pox-addr (B)

**Describe alternatives you've considered**
A) Wrap function calls of pox with functions that convert (response someType int) to (response someType uint).
B) Deploy a contract that adds this dummy parameter

@yknl Do you have more wishes?

**Comment by jcnelson** [comment]
Going to go ahead and close this due to inactivity.

It sounds like the issue can be mitigated with a wrapper contract.  However, I don't support changing all of the type signatures of `.pox-2` because I don't have a good understanding of what downstream client software will break by doing so.  Exchanges that offer stacking services could break, for example.

> B) I am frustrated that pool members can't specify where they want to receive their stacking rewards

`delegate-stx` takes an `optional` `pox-addr` tuple, which it sounds like achieves this?

**Comment by friedger** [comment]
The optional pox-addr is free pool operator's bitcoin reward address, not the pool member's address
