### ISSUE TITLE
<s>Re-running my benchmarks today, this PR now looks good when compared to #3326 in benchmarking.

### ISSUE THREAD

**Issue by kusai90** [stacks-network/stacks-blockchain#3341]
<s>Re-running my benchmarks today, this PR now looks good when compared to #3326 in benchmarking. 

_I was previously seeing better numbers for the other implementation, so it might be good for someone else to try benchmarking these and see if it is reproducible._</s>

The better numbers from before were when the caching was applied on top of the changes in #3326.

| Version | Commit | Num Tx | %-Full | Fees Collected (uSTX) | Time Spent (ms) |
| --- | --- | --- | --- | --- | --- |
| master | 378fc1b80e161ce1b82cc98b3802565222100816 | 105 | 4.97% | 25175605 | 33983.1 |
| #3326 | 6052447629436343d1ccd942a6a7d4381bfc670e | 1034 | 99.97% | 144993355 | 16822.8 |
| #3337 | 9a62096894b1d8de157e811384b7f44653a46a03 | 952 | 99.96% | 155684975 | 14121.9 |

_Originally posted by @obycode in https://github.com/stacks-network/stacks-blockchain/issues/3337#issuecomment-1276064427_

**Comment by obycode** [comment]
Hi @kusai90. Do you plan on helping with the benchmarking? If so that's great, thanks! Checkout the later version of that table, replicated below. Let me know if you have any questions.

| Version | Commit | Num Tx | %-Full | Fees Collected (uSTX) | Time Spent (ms) |
| --- | --- | --- | --- | --- | --- |
| master | 378fc1b80e161ce1b82cc98b3802565222100816 | 105 | 4.97% | 25175605 | 33983.1 |
| #3326 | faffe420d8c5dee8151a988d0f8bc1b7ebb227de | 1034 | 99.97% | 144993355 | 16604.9 |
| #3337 | 1586e86d20d8931c3e51804e337539f3b3c1d33a | 1097 | 100% | 189810290 | 15624.7 |

**Comment by jcnelson** [comment]
Treating as spam.
