### ISSUE TITLE
[sBTC] Convert `data relay` Python script to Rust

### ISSUE THREAD

**Issue by sergey-shandar** [stacks-network/stacks-blockchain#3477]
**Is your feature request related to a problem? Please describe.**
We would like to use only few programming languages. Currently, the main language for the repo is Rust. The specific [script](https://github.com/stacks-network/stacks-blockchain/blob/sbtc/contrib/tools/http_datarelay.py) is written in Python.

**Describe the solution you'd like**
We will use a Rust program instead. Also, we will have a Rust library for unit testing.

**Describe alternatives you've considered**
Keep it as a Python script but it will increase a number of languages in the repo. Also it is hard to use the Python script for Rust unit testing. 

**Additional context**

**Comment by jcnelson** [comment]
I'm personally fine with leaving it as-is if there are more important things to do, because this is ultimately throw-away code.  In a few weeks, the integration tests for stacking will be using one or more Stacks node instances (i.e. one per thread in the test), which will take care of replicating and serving the stacker data.

**Comment by sergey-shandar** [comment]
> I'm personally fine with leaving it as-is if there are more important things to do, because this is ultimately throw-away code. In a few weeks, the integration tests for stacking will be using one or more Stacks node instances (i.e. one per thread in the test), which will take care of replicating and serving the stacker data.

Make sense. However, I plan to use parts of the Rust code for the integration tests.
