### ISSUE TITLE
Manage bitcoin wallet with RPC calls

### ISSUE THREAD

**Issue by 0xbabo** [stacks-network/stacks-blockchain#3591]
The stacks node seems to be unnecessarily duplicating wallet management that is already handled better by the bitcoin node. Furthermore, it does this by demanding the user provide a private key in plaintext, while the bitcoin node can readily handle encrypted wallets. 

Wallet management should be done with RPC calls to the bitcoin node with an unlocked wallet (can be unlocked with [walletpassphrase](https://developer.bitcoin.org/reference/rpc/walletpassphrase.html)). Transactions can be submitted via [createrawtransaction](https://developer.bitcoin.org/reference/rpc/createrawtransaction.html). 

Relevant reading material: #898 and [Slope wallet postmortem](https://solana.com/news/8-2-2022-application-wallet-incident)

**Comment by igorsyl** [comment]
Thank you for your issue contribution. I've tagged this item to be addressed by a new Stacks core dev team spinning up soon.

**Comment by jcnelson** [comment]
This is not a priority for us.  The Stacks node needs to be responsible for generating its own Bitcoin transactions in order to ensure that it can reliably do so, regardless of which version of `bitcoind` the miner uses.  Moreover, the `bitcoind` node would also be managing a hot wallet, just as the Stacks node does, so there is no loss of security.  Closing as EWONTFIX.
