### ISSUE TITLE
/v2/pox misbehaves after the epoch boundary

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3594]
Just saw this on testnet at the 2.1 activation.

The /v2/pox endpoint's `current_burnchain_block_height` appears to be stuck at height 2422102, whereas the burnchain height at /v2/info returns 2422104.  Moreover, the pox-2 contract does not seem to have materialized -- I can't query the contract.

I tested this against https://stacks-node-api.testnet.stacks.co/v2/pox and https://stacks-node-api.testnet.stacks.co/v2/info.

@deantchi @CharlieC3 Can I get access to the logs and/or chainstate for one of these nodes?

**Comment by jcnelson** [comment]
Following up, it appears that the testnet explorer is stuck on tBTC height 2422100.

**Comment by deantchi** [comment]
its looks like the node is progressing, its currently at `2422106`, however, the api is stuck at `2422102`

**Comment by diwakergupta** [comment]
Seems instantiated to me:
https://explorer.stacks.co/txid/0x1bede82377127966b54032fce154577f685b413d726a8638bc40abbed2cf2a51?chain=testnet

@jcnelson can you confirm, and then close if appropriate?

One thing that's not clear to me is why did it materialize in block 2422153, if `activation_block_height` was set to 2422102. Is that expected behavior?

**Comment by diwakergupta** [comment]
Interesting:

<img width="305" alt="Screenshot 2023-03-01 at 11 16 54 AM" src="https://user-images.githubusercontent.com/15990/222198402-41764069-af8b-4451-b1f2-885c9642f38e.png">

That might explain?

**Comment by jcnelson** [comment]
Yes -- this behavior is consistent with Hiro's miner not being a 2.1 node, and thus failing to advance the chain for 53 blocks.
