### ISSUE TITLE
Top level Cargo.toml file shouldn't have package properties.

### ISSUE THREAD

**Issue by sergey-shandar** [stacks-network/stacks-blockchain#3809]
**Describe the bug**

The Rust cargo tool supports two types of cargo.toml files:
- for a package
- workspace

Our top level [Cargo.toml](https://github.com/stacks-network/stacks-blockchain/blob/master/Cargo.toml) contains both sets of properties, from a package and from a workspace.

**Steps To Reproduce**

- Some IDEs and plugins (for example VSCode) can't properly read and understand the file.
- Run `cargo build`
  ```
  warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
  package:   /.../stacks-network/stacks-blockchain/clarity/Cargo.toml
  workspace: /.../stacks-network/stacks-blockchain/Cargo.toml
  ```

**Expected behavior**

A simple command `cargo build` should build all packages in the repo without ignoring some of them.

A top level Cargo.toml should contain only workspace properties. For example https://github.com/Trust-Machines/stacks-sbtc/blob/main/Cargo.toml 

**Environment (please complete the following information):**

**Additional context**

We can use the `default-run` option if we need a default binary to run by `cargo run` command. See https://stackoverflow.com/questions/51785457/how-can-i-specify-which-crate-cargo-run-runs-by-default-in-the-root-of-a-cargo

**Comment by jcnelson** [comment]
> Some IDEs and plugins (for example VSCode) can't properly read and understand the file.

That sounds like a bug in your editor ;)

**Comment by sergey-shandar** [comment]
> > Some IDEs and plugins (for example VSCode) can't properly read and understand the file.
> 
> That sounds like a bug in your editor ;)

It's more than that. Editors use plugins, some of them (like rust-analyzer) are from `rust-lang` org. The problem is that the project inside of the `Cargo.toml` is kind of disconnected from the workspace. Plugins are confused about what they should do, either analyze the workspace or a project.

**Comment by jcnelson** [comment]
> It's more than that. Editors use plugins, some of them (like rust-analyzer) are from rust-lang org. The problem is that the package inside of the Cargo.toml is kind of disconnected from the workspace. Plugins and cargo are confused about what they should do, either analyze the workspace or the package. If we add the package to the workspace as a member, it will make much clear the overall repo structure and dependencies.

How so?  The project builds, tests run, and static checks like formatting all run without any problem.  Cargo isn't failing in its tasks here.  The problem as described is that your editor plugin doesn't know how to deal with a Cargo.toml that cargo treats as valid.  That's the plugin's fault, not cargo's.  It doesn't matter if the plugin is from the Rust-lang org; all that means is that they need to fix their plugin code, or fix cargo so it also treats Cargo.toml as invalid.  Since this project depends on cargo's ability to build the project, not a particular editor's ability to parse Cargo.toml, I'm going to consider this to be an issue with your local machine.

That said, there is a need to factor the code into more workspaces, but for entirely different reasons and somewhat different outcomes.  Multiple workspaces will:

* speed up local build times during development, since unmodified workspace members will not need to be rebuilt

* force us to consider and implement the "narrow waist" APIs between code modules, leading to better isolation between them

* enable more fine-grained testing, and enable automated testing like fuzzing and property testing

* improve test parallelization

* enable different parts of the code (namely, public data structures and their codecs) to be re-licensed for more permissive use

While the result of creating multiple workspaces would have the effect of producing a top-level Cargo.toml without package properties, the means of getting there would look very different.  In particular, there would be more to it than just moving `src/` into `blockstack-core/src`.

**Comment by sergey-shandar** [comment]
> > It's more than that. Editors use plugins, some of them (like rust-analyzer) are from rust-lang org. The problem is that the package inside of the Cargo.toml is kind of disconnected from the workspace. Plugins and cargo are confused about what they should do, either analyze the workspace or the package. If we add the package to the workspace as a member, it will make much clear the overall repo structure and dependencies.
> 
> How so? The project builds, tests run, and static checks like formatting all run without any problem. Cargo isn't failing in its tasks here. The problem as described is that your editor plugin doesn't know how to deal with a Cargo.toml that cargo treats as valid. 

Sorry, I've added late few more signs of the problem. For example, running a simple `cargo build` suppose to build everything without warnings. Currently there are warnings:

```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /.../stacks-network/stacks-blockchain/clarity/Cargo.toml
workspace: /.../stacks-network/stacks-blockchain/Cargo.toml
```

Plugin IDEs and build warnings are only a few consequences of the problem. The root of the problem is the ambiguous `Cargo.toml` at the root. If we put package properties from the root `Cargo.toml` into another `Cargo.toml`, then it should solve this ambiguity. 

> That said, there is a need to factor the code into more workspaces, but for entirely different reasons and somewhat different outcomes. Multiple workspaces will:

I think we should have only one workspace per repo to avoid build and dependency conflicts.

**Comment by zone117x** [comment]
I've noticed this issue as well. From both the command line warnings, and rust-analyzer. 

For example when trying to build a specific package from the root dir, cargo outputs a warning and incorrectly mentions the `clarity` package, yet it does build and output the expected package (stacks-node not clarity):
```shell
$ cargo build -F slog_json -p stacks-node --bin stacks-node --release
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/matt/txfail/stacks-blockchain/clarity/Cargo.toml
workspace: /home/matt/txfail/stacks-blockchain/Cargo.toml
...
Finished release [optimized + debuginfo] target(s) in 0.38s
```

If I `cd ./testnet/stacks-node` and build from that directory, it logs the same warning and incorrectly logs the `clarity` package.

With vscode/rust-analyzer, it will often have issues and stop working, I _think_ because of the workspace and package layout but not sure.

**Comment by jcnelson** [comment]
> I think we should have only one workspace per repo to avoid build and dependency conflicts.

That's not going to happen anytime soon, for several reasons:

* It degrades the release process.  Right now, we release signed source code tarballs along with signed binaries so that end users who build from source (and we do have quite a few) only need to authenticate one file's hash.  Treating different workspaces as different repos would significantly increase the number of files we'd need to publish, and increase the number of files users would need to authenticate.  Keeping the source within one tarball minimizes the amount of operational errors that can occur.

* It makes it much harder to address cross-cutting concerns.  There are aspects of the codebase that need to be consistent which span multiple modules (e.g. logging, metrics collection, code standards, etc.).  Putting different workspaces into different repos makes the act of implementing and maintaining these concerns much more challenging, because now multiple PRs must be submitted and approved _atomically_, which is a much harder task to coordinate and execute than a single PR review.

* It provides more opportunities for code quality and CI/CD to degrade.  Instead of having one set of code guidelines and one CI/CD pipeline, we'd now have several.  Each one would need to be maintained; even if it was done by one person, it linearly scales up the amount of work they'd have to do.  We already have a lot of room for improvements on our existing CI/CD process; creating more CI/CD pipelines would make this harder.

* It makes building from source more error-prone.  Now you have to check out and build all of the separate repositories in order, instead of just downloading one repository and running `cargo build`.  This applies to both users and CI/CD.

Also, what "build and dependency conflicts" arise today?  `cargo build` runs successfully.

**Comment by jcnelson** [comment]
Look, I'm not poo-poo-ing the idea of factoring the code so that there are no longer any package properties in the Cargo.toml.  I'm instead trying to push us in the direction of factoring the code into workspace members in such a way that it addresses some very real quality-of-life problems that we're already slated to tackle this quarter anyway.  A refactored Cargo.toml file will be had one way or another.

**Comment by sergey-shandar** [comment]
> Look, I'm not poo-poo-ing the idea of factoring the code so that there are no longer any package properties in the Cargo.toml. I'm instead trying to push us in the direction of factoring the code into workspace members in such a way that it addresses some very real quality-of-life problems that we're already slated to tackle this quarter anyway. A refactored Cargo.toml file will be had one way or another.

I think, there are two separate issues: 

1. Remove ambiguity of the top level `Cargo.toml` (this issue). 
2. how we can optimize build/test/sign process. note: I'm not saying that we need multiple repos. Actually, I'm vote with my two hands for a mono-repo. My understanding is that one root level workspace should be enough for any repo with any number of packages for any scenario. IMHO, the purpose of a workspace is reduce build time, reduce build/dependency conflicts, reuse artifacts and dependencies. So, in theory, one big workspace should only improve CI/CD and testing. I may not know something but this my impression. I'm not sure how multiple workspace can improve CI/CD speed.

**Comment by stjepangolemac** [comment]
I was going to create a similar issue but then found this one.

I've read the discussion and I believe there's a misunderstanding. @jcnelson mentions "workspace" and "multiple workspaces" several times where from context it looks like he might mean "package" and "multiple packages".  If this is the case then both @jcnelson and @sergey-shandar are thinking along the same lines.

@sergey-shandar is suggesting to have multiple projects in a single workspace per repo, and have only this repo - as is the standard in most Rust codebases. From the file structure that looks like something we have here. The problem is that the main `Cargo.toml` file defines the root, or itself, as another workspace member. I haven't seen this type of setup before. Rather than this being allowed by design, I suspect it to be a configuration quirk that is allowed "by accident".

I discovered this independently when I wanted to use workspace dependencies for the new `stacks-core` package in the workspace. It appears there are no workspace dependencies as the main `Cargo.toml` file defines them only for the binaries and libraries in the root workspace member.

I agree with both of you in some way. I wouldn't call this kind of a setup wrong, but it's something that looks and feels wrong, even though it's supported. I believe it should be resolved and that we should define dependencies on the workspace level, unless there's a reason not to do it. The issues @jcnelson mentioned above might not be issues if we've misunderstood each other.

**Comment by sergey-shandar** [comment]
> I was going to create a similar issue but then found this one.
> 
> I've read the discussion and I believe there's a misunderstanding. @jcnelson mentions "workspace" and "multiple workspaces" several times where from context it looks like he might mean "package" and "multiple packages". If this is the case then both @jcnelson and @sergey-shandar are thinking along the same lines.
> 
> @sergey-shandar is suggesting to have multiple projects in a single workspace per repo, and have only this repo - as is the standard in most Rust codebases. From the file structure that looks like something we have here. The problem is that the main `Cargo.toml` file defines the root, or itself, as another workspace member. I haven't seen this type of setup before. Rather than this being allowed by design, I suspect it to be a configuration quirk that is allowed "by accident".
> 
> I discovered this independently when I wanted to use workspace dependencies for the new `stacks-core` package in the workspace. It appears there are no workspace dependencies as the main `Cargo.toml` file defines them only for the binaries and libraries in the root workspace member.
> 
> I agree with both of you in some way. I wouldn't call this kind of a setup wrong, but it's something that looks and feels wrong, even though it's supported. I believe it should be resolved and that we should define dependencies on the workspace level, unless there's a reason not to do it. The issues @jcnelson mentioned above might not be issues if we've actually misunderstood each other.

I use definitions from the Rust book. Also, I made a mistake initially, I used `project` instead of `package`.
https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

For me, there are two possible structures for a repo with multiple `packages`.

1. just reference a package from one to another and a root of the repo is also a package. For example
   ```toml
   # a/Cargo.toml
   [package]
   name = "a"
   ```
   ```toml
   # Cargo.toml
   [package]
   name = "main"
   [dependencies]
   a = { path = "../a" }
   ```
2. with a workspace. 
   ```toml
   # a/Cargo.toml
   [package]
   name = "a"
   ```
   ```toml
   # main/Cargo.toml
   [package]
   name = "main"
   [dependencies]
   a = { path = "../a" }
   ```
   ```toml
   # Cargo.toml
   [workspace]
   members = [ "a", "main"]   
   ```

I'm ok with either, but I prefer # 2 because it doesn't mix the `main` project with everything else and it has much cleaner structure.

The problem with the current Stacks repo, that it's a mix of 1 and 2 :-) Long time ago, there were no workspaces in Rust Cargo, so I understand why it happened with Stacks repo.
