### ISSUE TITLE
Nakamoto: Mocked implementation of Nakamoto ProcessedBurnDB

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3857]
This should be a struct with the necessary methods for returning
mocked data to its consumers. Initially, this should be relatively
few methods. It will be more clear which methods exactly are
necessary here once implementation on the other milestone 1 components
starts, but an educated guess of those methods is:

```
get_canonical_burn_block() -> Result<Option<BurnchainHeaderHash>, Error>
/// Return true if `ancestor` is either equal to `other` or an ancestor of `other`. False otherwise.
is_ancestor_of(ancestor: &BurnchainHeaderHash, other: &BurnchainHeaderHash) -> Result<bool, Error>
get_producer_set(at: &BurnchainHeaderHash) -> Result<Vec<StacksAddress>, Error>
get_stacker_set(at: &BurnchainHeaderHash) -> Result<Vec<StacksAddress>, Error>
```

Note: after M1, when the real implementation of `ProcessedBurnDB`
happens, processing in this DB should occur somewhat independently
of processing in the `NakamotoChainState`. It will just need to
stop processing if it gets to a reward cycle boundary.

**Comment by jcnelson** [comment]
Nakamoto is going to reuse the current mining process instead of requiring producer sets.  The only differences between the `SortitionDB` and Nakamoto are:

* There will be a `NakamotoBlockCommitOp` structure, which has slightly different validation rules than `LeaderBlockCommitOp`.  Namely, the `block_header_hash` is now interpreted as a `StacksBlockId`, and references the _previous_ miner's _first-produced_ Nakamoto Stacks block.
* There will be a new table for valid, processed `nakamoto_block_commit` transactions.
* There will be complementary APIs for storing and querying `NakamotoBlockCommitOp`s in addition to `LeaderBlockCommitOp`s.
